INSERT INTO `{tablepre}adflash` (`id`, `title`, `linkurl`, `thumb`, `orders`) VALUES (1, '', '', 'images/default/thumb_1.jpg', 1);
INSERT INTO `{tablepre}adflash` (`id`, `title`, `linkurl`, `thumb`, `orders`) VALUES (2, '', '', 'images/default/thumb_2.jpg', 3);
INSERT INTO `{tablepre}adflash` (`id`, `title`, `linkurl`, `thumb`, `orders`) VALUES (3, '', '', 'images/default/thumb_1.jpg', 2);

INSERT INTO `{tablepre}articles_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`,  `listnum`,  `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(1, '公司简介','','','', NULL, 10, NULL, NULL, NULL, NULL, 0, 0, 0, 0);
INSERT INTO `{tablepre}articles_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`,  `listnum`,  `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(2, '公司新闻','','','', NULL, 10, NULL, NULL, NULL, NULL, 0, 0, 0, 0);
INSERT INTO `{tablepre}articles_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`,  `listnum`,  `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(3, '行业新闻','','','', NULL, 10, NULL, NULL, NULL, NULL, 0, 0, 0, 0);



INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(1, '关于我们', '', '', '', '', NULL, NULL, '', '', '', '关于我们', '关于我们', '匿名', 1, '', 360, 1, 0, 0, 0, 1280156700, 1319575139);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(2, '联系我们', '', '', '', '', NULL, NULL, '#f00', '', '', '', '联系我们12', '匿名', 1, '', 222, 1, 0, 0, 0, 1280156700, 1319575127);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(3, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '我们向往更新更快更强', 'admin', 2, '', 6, 1, 1, 1, 1, 1319236560, 1344517707);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(4, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '我们向往更新更快更强', 'admin', 2, '', 6, 1, 1, 1, 1, 1319236560, 1344517706);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(5, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 3, 1, 1, 1, 1, 1324513440, 1344517706);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(6, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 3, 1, 1, 1, 1, 1324513500, 1344517692);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(7, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 11, 1, 1, 1, 1, 1324513500, 1344517683);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(10, 'ZCNCMS最新版本上线欢迎测试', '', '', '', '', '', '', '', '', '', 'zcncms新版本上线 zcncms zcncms专注于内容管理希望广大的用户积极测试', '<span style="color: rgb(102, 102, 102); text-align: justify; "></span><p style="text-align: justify; margin-top: 0px; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(102, 102, 102); "></p><p style="text-align: justify; margin-top: 0px; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(102, 102, 102); ">zcncms新版本上线&nbsp;<a href="http://www.zcncms.com/" target="_parent" style="color: rgb(0, 102, 204); ">zcncms</a>&nbsp;zcncms专注于内容管理，秉承简单实用做的宗旨，以务实作为根本的出发点，立足于内容管理的开发。希望广大的用户积极测试，zcncms最新版本上线的同时，后续的开发也在继续进行中，希望大家一如既往的支持zcncms也希望大家对zcncms提出更高的要求。在测试过程中出现的任何bug都可以通过论坛反馈到开发组，并且您也可以对更新版本提出自己的建议和见解。好的建议和意见将会在考评之后进入开发流程，我们将会尽最大努力不辜负广大用户的期待。</p><p style="text-align: justify; margin-top: 0px; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(102, 102, 102); ">zcncms新增<a href="http://www.zcncms.com/?c=articles&amp;a=list&amp;classid=4" target="_blank" style="color: rgb(0, 102, 204); ">zcncms帮助中心</a>和<a href="http://www.zcncms.com/?c=articles&amp;a=list&amp;classid=5" target="_blank" style="color: rgb(0, 102, 204); ">zcncms产品项目介绍</a>，欢迎访问帮助中心和选用我们提供的服务。</p><p style="text-align: justify; margin-top: 0px; margin-right: 0px; margin-bottom: 10px; margin-left: 0px; color: rgb(102, 102, 102); "></p><span style="color: rgb(102, 102, 102); text-align: justify; "></span> ', 'admin', 3, 'images/default/thumb_1.jpg', 30, 1, 1, 1, 1, 1325219220, 1344521620);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(9, 'ZCNCMS最新版本上线欢迎测试', '', '', '', '', '', '', '', '', '', 'zcncms新版本上线 zcncms zcncms专注于内容管理希望广大的用户积极测试', '<span style="font-family:''Microsoft YAHEI'', Arial, Helvetica, sans-serif;LINE-HEIGHT: 18px"></span><p style="TEXT-ALIGN: justify; MARGIN: 0px 0px 10px; COLOR: rgb(102,102,102)">zcncms新版本上线&nbsp;<a style="COLOR: rgb(0,102,204); TEXT-DECORATION: underline" href="http://www.zcncms.com/" target="_parent">zcncms</a>&nbsp;zcncms专注于内容管理，秉承简单实用做的宗旨，以务实作为根本的出发点，立足于内容管理的开发。希望广大的用户积极测试，zcncms最新版本上线的同时，后续的开发也在继续进行中，希望大家一如既往的支持zcncms也希望大家对zcncms提出更高的要求。在测试过程中出现的任何bug都可以通过论坛反馈到开发组，并且您也可以对更新版本提出自己的建议和见解。好的建议和意见将会在考评之后进入开发流程，我们将会尽最大努力不辜负广大用户的期待。</p><p style="TEXT-ALIGN: justify; MARGIN: 0px 0px 10px; COLOR: rgb(102,102,102)">zcncms新增<a style="COLOR: rgb(0,102,204); TEXT-DECORATION: underline" href="http://www.zcncms.com/?c=articles&amp;a=list&amp;classid=4" target="_blank">zcncms帮助中心</a>和<a style="COLOR: rgb(0,102,204); TEXT-DECORATION: underline" href="http://www.zcncms.com/?c=articles&amp;a=list&amp;classid=5" target="_blank">zcncms产品项目介绍</a>，欢迎访问帮助中心和选用我们提供的服务。</p>', 'admin', 2, 'images/default/thumb_2.jpg', 55, 1, 0, 0, 1, 1324513800, 1344521576);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(11, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 3, '', 0, 1, 1, 1, 0, 1344517740, 1344517760);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(12, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 3, '', 0, 1, 1, 1, 1, 1344517740, 1344517766);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(13, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', 'admin', 3, '', 0, 1, 1, 1, 1, 1344517740, 1344517779);
INSERT INTO `{tablepre}articles` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(14, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '我们向往更新更快更强我们向往更新更快更强我们向往更新更快更强我', '', 'admin', 3, '', 0, 1, 1, 1, 1, 1344517740, 1344517836);

INSERT INTO `{tablepre}books_class` (`id`, `title`, `orders`) VALUES(1, '咨询提问', 0);
INSERT INTO `{tablepre}books_class` (`id`, `title`, `orders`) VALUES(2, '在线留言', 0);

INSERT INTO `{tablepre}links_class` (`id`, `title`, `orders`) VALUES(1, '友情链接', 0);

INSERT INTO `{tablepre}links` (`id`, `title`, `linkurl`, `thumb`, `classid`, `starttime`, `endtime`) VALUES(1, 'zcncms', 'http://www.zcncms.com', '', 1 , 0, 0);

INSERT INTO `{tablepre}members_class` (`id`, `title`, `orders`) VALUES(1, '待审核', 0);
INSERT INTO `{tablepre}members_class` (`id`, `title`, `orders`) VALUES(2, '免费用户', 0);



INSERT INTO `{tablepre}users_class` (`id`, `title`, `orders`) VALUES(1, '系统管理员', 0);
INSERT INTO `{tablepre}users_class` (`id`, `title`, `orders`) VALUES(2, '管理员', 0);
INSERT INTO `{tablepre}users_class` (`id`, `title`, `orders`) VALUES(3, '编辑', 0);


INSERT INTO `{tablepre}downloads_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `listnum`, `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(1, '下载分类1', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0);
INSERT INTO `{tablepre}downloads_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `listnum`, `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(2, '下载分类2', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0);

INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(1, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518160, 1344518211);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(2, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518220, 1344518221);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(3, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518220, 1344518225);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(4, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518220, 1344518229);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(5, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 2, 1, 0, 0, 1, 1344518220, 1344518329);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(6, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 0, 1, 0, 0, 0, 1344518220, 1344518323);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(7, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 0, 1, 0, 0, 0, 1344518220, 1344518317);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(8, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 0, 1, 0, 0, 0, 1344518220, 1344518307);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(9, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 0, 1, 0, 0, 0, 1344518340, 1344518348);
INSERT INTO `{tablepre}downloads` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `dlinkname`, `dlink`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(10, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 2, '', 1, 1, 0, 0, 1, 1344518340, 1344518363);

INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(1, '企业简介', '#', '_self', 0, 0, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(2, '关于我们', '?c=articles&a=show&id=1', '_blank', 1, 1, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(3, '联系我们', '?c=articles&a=show&id=2', '_blank', 1, 1, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(4, '企业新闻', '?c=articles&a=list&classid=2', '_self', 0, 0, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(5, '行业新闻', '?c=articles&a=list&classid=3', '_self', 0, 0, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(6, '下载中心', '#', '_self', 0, 0, 0, 0),
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(7, '下载分类1', '?c=downloads&a=list&classid=1', '_self', 6, 6, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(8, '下载分类2', '?c=downloads&a=list&classid=2', '_self', 6, 6, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(9, '产品中心', '?c=products&a=list&classid=1', '_self', 0, 0, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(10, '留言', '?c=books&a=add&classid=1', '_self', 0, 0, 0, 0);
INSERT INTO `{tablepre}menus` (`id`, `title`, `linkurl`, `target`, `rootid`, `parentid`, `level`, `orders`) VALUES(11, '留言反馈', '?c=books&a=list&classid=1', '_self', 0, 0, 0, 0);

INSERT INTO `{tablepre}products_class` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `listnum`, `linkurl`, `thumb`, `template`, `intro`, `rootid`, `parentid`, `level`, `orders`) VALUES(1, '产品分类1', '', '', '', '', '', '', '', '', '', 0, 0, 0, 0);

INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(1, '产品图片测试', '', '', '', '', '', '', '', '', '', '200', '1-985', '', '', 'admin', 1, 'images/default/thumb_1.jpg', 4, 1, 0, 0, 0, 1344518340, 1344521529);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(2, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518340, 1344518385);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(3, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518340, 1344518387);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(4, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518340, 1344518389);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(5, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 0, 1, 0, 0, 0, 1344518340, 1344518395);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(6, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 1, 1, 0, 0, 0, 1344518340, 1344518398);
INSERT INTO `{tablepre}products` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `price`, `standard`, `intro`, `content`, `author`, `classid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`) VALUES(7, '我们向往更新更快更强', '', '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, '', 3, 1, 0, 0, 0, 1344518400, 1344518404);

INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(1, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_2.jpg', 0, 1, 0, 0, 0, 1344520800, 1344520805, 0);
INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(2, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_1.jpg', 0, 1, 0, 0, 0, 1344520800, 1344520830, 0);
INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(3, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_2.jpg', 0, 1, 0, 0, 0, 1344520800, 1344520841, 0);
INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(4, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_1.jpgg', 0, 1, 0, 0, 0, 1344520800, 1344520849, 0);
INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(5, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_2.jpg', 0, 1, 0, 0, 0, 1344520800, 1344520859, 0);
INSERT INTO `{tablepre}products_photo` (`id`, `title`, `seotitle`, `seokeyword`, `seointro`, `filename`, `fromtitle`, `fromlinkurl`, `titlecolor`, `linkurl`, `template`, `intro`, `content`, `author`, `productid`, `thumb`, `clicks`, `isplay`, `istop`, `ishot`, `isgood`, `addtime`, `authortime`, `orders`) VALUES(6, '', '', '', '', '', '', '', '', '', '', '', '', 'admin', 1, 'images/default/thumb_1.jpg', 0, 1, 0, 0, 0, 1344520860, 1344520869, 0);